version: '3.8'

services:
  go_app:
    image: ${CONTAINER_IMAGE}
    networks:
      - app_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - go_app
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
