version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.bootstrap.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
    networks:
      - app_net

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    command: [
      "certonly", "--webroot",
      "-w", "/var/www/certbot",
      "--email", "${CERTBOT_EMAIL}",
      "--agree-tos",
      "--no-eff-email",
      "--non-interactive",
      "--force-renewal",
      "-d", "${DOMAIN}"
    ]

networks:
  app_net:
    driver: bridge
