package database

var IDENTITY_TABLE_NAME = "iam"
var ACCOUNT_DETAIL_TABLE_NAME = "accountDetail"
var PERSONAL_DETAIL_TABLE_NAME = "personalDetail"
var COMPANY_TABLE_NAME = "company"
var COMPANY_TYPE_TABLE_NAME = "companyType"
var USER_DETAIL_TABLE_NAME = "userDetail"
var MEMBERSHIP_PLAN_TABLE_NAME = "membershipPlan"
var EVENT_ROOMS_TABLE_NAME = "EventRoom"
var INVENTORY_EQUIPMENT_TABLE_NAME = "Equipment"
var INVENTORY_ITEM_TABLE_NAME = "Item"
var EVENTS_TABLE_NAME = "Event"
var SCHEDULED_EVENTS_TABLE_NAME = "ScheduledEvent"
var MENU_ITEM_TABLE_NAME = "MenuItem"
var MENU_ITEM_PRICING_TABLE_NAME = "MenuItemPricing"
var ORDERS_TABLE_NAME = "Orders"
var ORDER_ITEM_TABLE_NAME = "OrderItem"
var MENU_ITEM_CATEGORY_TABLE_NAME = "MenuItemCategory"
var BUDGET_ITEM_TABLE_NAME = "BudgetItem"
var BUDGET_CATEGORY_TABLE_NAME = "BudgetCategory"
var BUDGET_CATEGORY_TYPE_TABLE_NAME = "BudgetCategoryType"
var ASSET_TYPE_TABLE_NAME = "AssetType"
